---
title: A wire loop game
hero_image: images/banner.png
description: Make a classic wire-loop game with Scratch and a Raspberry Pi
meta_title: Raspberry Pi Projects | Scratch | Wire loop game
meta_description: The third Raspberry Pi project in the Physical computing with Scratch path. Follow step-by-step instructions to make a classic wire-loop game with a buzzer. 
version: 4
listed: true
copyedit: true
last_tested: '2021-02-22'
steps:
  - title: You will make
  - title: Wire and test a buzzer
  - title: Add a button
    completion:
      - engaged
  - title: Build your wire loop game
  - title: Add a score
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: What next?
