title: A wire loop game
hero_image: images/banner.png
description: Make a classic wire-loop game with Scratch and a Raspberry Pi
version: 4
listed: true
copyedit: true
last_tested: "2021-02-22"
steps:
  - title: Introduction
  - title: Wire and test a buzzer
  - title: Add a button
    completion: engaged  
  - title: Build your wire loop game
  - title: Add a score
    completion: internal 
  - title: Reflection
    completion: external 
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3       
  - title: Upgrade your project
  - title: What next?
 
