title: rpi-wire-loop-game-scratch
hero_image: images/banner.png
description: rpi-wire-loop-game-scratch description
version: 4
listed: false
copyedit: false
last_tested: "2021-02-22"
steps:
  - title: Introduction
  - title: Wire and test a buzzer
  - title: Add a button
  - title: Build your wire loop game
  - title: Add a score
  - title: Reflection
  - title: What next?